name: codearabia
favicon: null
layout_spectrum: 0.1687226858921349
typography_spectrum: 0.11234066914767027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4501736608799547
  lightness: 0.5021613866556436
  saturation: 0.9152030490804464
  rhythmicContrast: 0.04359612986445427
purpose: []
